### PR TITLE
Decompose generator functions

### PR DESCRIPTION
**Pull request by latiif**
This PR refactorizes `/src/scripts/generator.js` to make it easier to export some of its inner functions as discussed in #59.

- Extract inner functions from within `generate()` to their own top-level functions.
- Inner state is now represented by a config object that's passed around and is instantiated once in `generate()`.
- Runs a formatter on the file to fix various formatting issues. 

This PR doesn't introduce new functionality.

This PR doesn't export any new functions from `/src/scripts/generator.js`.

### CODE REVIEW

**Comment by latiif** [comment]
It seems like there's somethin weird happening with the checks here. it complains about a deprecated way to import `octokit` which I've never found in the codebase, then it suddenly fails because 

_Error: Resource not accessible by integration_ 

Is there anything I can do on my part?

**Comment by Azgaar** [comment]
Hello, @latiif. Do worry about it, it's just an automated greeting that is failing for some reason. I will try to check the PR today

**Comment by Azgaar** [comment]
Hello, I did quickly check. I'm nice, but refactoring is still required, I can see mainly cosmetical changes. If it was your aim, it's ok, we can merge.

A few remarks:
* You are commenting where it's not required (I do the same, but it's a bad practice)
* Adding OOP just for a Config does not help. It just make the code more verbose. It should either solid OOP, or just imperative code as we have now
*  Some inner functions are very verbose, it would be nice to move them out as well. E.g. colors setup for patterns should be in dataModel.js, not in generator.js (I know it's my code, just noticing that it would be nice to get it fixed)

**Comment by latiif** [comment]
> You are commenting where it's not required (I do the same, but it's a bad practice)

This is a spill-over habbit from Golang, comments are required when declaring a capitalized type. Good to know this doesn't transfer to JS.

> Adding OOP just for a Config does not help. It just make the code more verbose. It should either solid OOP, or just imperative code as we have now

I'm new to JS. I would've liked to use a companion data-class object . But JS apparently doesn't have those. So I opted for a class. The reason I'm using a class, is that I can pass this object across the different functions (instead of passing separated parameters). This also allows me to pass stuff by reference, as some functions change the values of these parameters.  Maybe I can just define them as JSON object instead of a class. 
Another option is to define them as top level variables, but this doesn't seem like much of an improvement.

> Adding OOP just for a Config does not help. It just make the code more verbose. It should either solid OOP, or just imperative code as we have now

_This_ refactorization is in no shape or form final. It's just an intial trial at doing this. This suggestion make a lot of sense now that I've looked at it.

**Comment by Azgaar** [comment]
Thank you, Latiif. I believe it's fine, I can merge once you confirm changes are done.

**Comment by latiif** [comment]
I think this PR is good to be merged now.

**Review by Azgaar — APPROVED** [review]

**Comment by Azgaar** [comment]
Merging, but further refactoring required.

**Pull request merged**
