### PR TITLE
Support two or three tinctures for some charges

### PR DESCRIPTION
**Pull request by Blipz**

### CODE REVIEW

**Comment by Azgaar** [comment]
Hello. It looks great. Will need some time to check

**Comment by Blipz** [comment]
Some charges with hardcoded colors (like castle, crown2...) could be added to this, if needed.

Also, the changes to SVG files are minimal (adding class to elements and splitting paths) but ideally, I'd like to modify some of them a bit more, like the dragon ones to make the scales on their belly use the secondary tincture.

**Comment by Azgaar** [comment]
I believe all charges that can be multi-colored should support multiple colors. Otherwise it looks weird. But on auto-generation it should come pretty rarely. Maybe we can define multi-color probability in config.

**Comment by Azgaar** [comment]
@Blipz, any other work expected here? I mean for this particular Pull Request.

**Comment by Blipz** [comment]
I think I'm done here, unless maybe for the wingSword charge where I don't know if we should use a carnation tincture for the hand, or keep it of the same color as the wing.

**Comment by Azgaar** [comment]
Checked the code, it looks there is some work to be done, started as https://github.com/Azgaar/Armoria/tree/multicolor2

**Comment by Azgaar** [comment]
@Blipz, please merge my changes to your branch here: https://github.com/Blipz/Armoria/pull/1. Then I will merge this PR

**Review by Azgaar — APPROVED** [review]

**Pull request merged**
