### PR TITLE
SvelteKit migration

### PR DESCRIPTION
**Pull request by Blipz**
Regarding the Armoria API integration:

- Image compression was not ported, as it's unclear to me what is the best way to handle it
- API endpoints were kept as is, but I wonder if it's useful to keep both `/format/size/seed` and `?format=&size=&seed=` (for now I redirected the former to the latter, which may not be ideal)
- Claiming API could not be fully tested with a real MongoDB database

### CODE REVIEW

**Comment by Azgaar** [comment]
Hi @Blipz, I suggest to merge it to another branch, not master, and deploy it from there. I will allow us to see how it works before switching from the current version. I hope I can work on it this weekend.

**Comment by Blipz** [comment]
OK, will push in sveltekit branch.

**Comment by Azgaar** [comment]
Hi @Blipz, can you please resolve the conflicts so that we can merge it to the branch?

**Comment by Blipz** [comment]
These changes are already merged in the sveltekit branch. The PR can be closed unless we want to keep it for discussing the topic.

**Comment by Azgaar** [comment]
Ok, makes sense. Let's close it and then raise a new one if required.

**Comment by Azgaar** [comment]
Had to create new PR: #188

**Pull request closed without merging**
