### PR TITLE
Support patterns for charges and ordinaries

### PR DESCRIPTION
**Pull request by Blipz**
Even though the backend supported it, there was no UI for patterned charges and ordinaries.

With this PR, patterns and semies can now be selected to color ordinaries and charges (including secondary and tertiary coloring).

Note 1: the default probability of patterned charges/ordinaries has not been modified here (so still at 0). Also, maybe the chance system should differentiate between charges and ordinaries.

Note 2: the UI could probably be improved in some way. With both multicolor and pattern support, coloring a charge might become confusing to users.

### CODE REVIEW

**Comment by Azgaar** [comment]
Can you please add a description on what is actually does? It's not 100% clear. Maybe can reuse some description from https://github.com/Azgaar/Armoria/discussions/174

**Comment by Azgaar** [comment]
Is it ready for merging?

**Comment by Blipz** [comment]
> Is it ready for merging?

Yes. UI could be improved later if needed.

**Comment by Azgaar** [comment]
Ok, let's merge.

**Pull request merged**
