### PR TITLE
Make all charges patternable

### PR DESCRIPTION
**Pull request by Blipz**

### CODE REVIEW

**Comment by Azgaar** [comment]
Hello. Looks good, but it's a big change. Would need to change Map Generator and Armoria API accordingly. As we change charges data here, it would make sense to add positions to the new object as well.

**Comment by Blipz** [comment]
Do you mean the default position when a charge is added?

**Comment by Azgaar** [comment]
Yes, list of positions

**Comment by Azgaar** [comment]
In `dataModel` there is a `positions` object that can be refactored. Data can be added to Charges and Ordinaries data

**Comment by Azgaar** [comment]
Sorry for being unclear, I have work in parallel, trying to do 10 things at the same time

**Comment by Blipz** [comment]
I did miss this part of the code. That's done now, as well as the natural tincture part.

**Comment by Azgaar** [comment]
Not sure I can review before the weekend. Also would need to do the same in FMG and API.

**Comment by Azgaar** [comment]
Started to work on it yesterday, but my macbook has died, so it will take more time now...

**Comment by Blipz** [comment]
The wolfStatant charge has to be adapted, too.

**Pull request merged**
