### PR TITLE
Various new charges

### PR DESCRIPTION
**Pull request by Blipz**
This adds a bunch of charges, mostly extracted from WappenWiki.

### CODE REVIEW

**Comment by Azgaar** [comment]
It looks really good, will try to review and merge soon

**Comment by Azgaar** [comment]
Need to update config file with charges

**Comment by Blipz** [comment]
> Need to update config file with charges

I was not sure which PR you want to merge first, so I avoided pushing this file. If needed I can remove the classes for multicolor in this PR.

**Comment by Azgaar** [comment]
Let's have charges here, including the config file update

**Comment by Blipz** [comment]
In progress of resolving the conflicts.

**Comment by Azgaar** [comment]
Reviewed once again, looks really good, have no complains or whatsoever

**Comment by Blipz** [comment]
Sorry this was accidentally closed (not very accustomed to the Github workflow), should I recreate a PR?

**Comment by Azgaar** [comment]
Yes please

**Pull request closed without merging**
