### PR TITLE
Add keyboard shortcuts for Undo and Redo

### PR DESCRIPTION
**Pull request by varlevi**
Having to go and press the undo and redo buttons can be tedious. Having these keyboard shortcuts makes using this app more intuitive and efficient.

### CODE REVIEW

**Comment by Azgaar** [comment]
Hello @varlevi. Thanks for the PR! I like it, maybe keys selection is arguable, but still.
I am going to publish alpha soon, so more changes are coming. Actually need to fix animations, responsive UI. Hotkeys is good addition.

**Comment by Azgaar** [comment]
By the way, tool is not yet published, so I don't have feedback from devs. How do you find its design?

**Comment by varlevi** [comment]
Glad you found the PR helpful. I'm not an expert on Svelte, so there may be a better way to implement hotkeys like Ctrl+Z, instead of just Z, but since the application doesn't use keys for normal typing, I think it works fine. As for the design, it is very clean and organized, and I think the application style is both modern but also fitting with the medieval/fantasy theme. A few things, though, that probably deserve their own issues.

1. When you choose a shield type, you can't get back to having random shields show up in the gallery. Having a choice to go back to having random shield shapes would be helpful.

2. Secondly, although this may be a problem having to do with me running the application locally, is that the icons are not showing up correctly. You can see a picture below of the Options drop-down, where all the icons are lock icons. This is especially a problem because it makes it look like they're "premium" features that are locked to the user. Again, though, this could be a problem with my local environment. I'm running a Linux box, so I don't have the icons normally installed on a Mac or Windows machine. This problem will need more debugging.

options-menu

3. One more small thing is that when adding charges, the letter L (as in Like) and the letter I (as in Ice) look the same in the letters overlaying the shield, which could be slightly confusing to some people.

sheild

Also, as you mentioned, the responsive UI still needs some alignment, but other than that, the application is well-designed and works very well. Hopefully, my _hopefully_ constructive criticism is helpful!

**Comment by Azgaar** [comment]
Hello. Typing is used, so I have amended hotkey function to handle typing. Also added more hotkeys, now it's much easier to work with.

> When you choose a shield type, you can't get back to having random shields show up in the gallery. Having a choice to go back to having random shield shapes would be helpful.

That's bad that this option is not obvious! You just need to click on Lock icon to restore default value, then refresh the screen.

As for locks - they are supposed to be locks. I know it looks weird. So maybe just need to add a "saved options" manager to allow users manually edit it. No sure, that's not what most applications use.

"I" and "l" - I agree, it's an issue. I will fix it with font change to monospace. It looks not so good, but more clear.

Thanks for the feedback! BTW, I published new version.

**Pull request merged**
