### PR TITLE
Point at the local copy of the language data, autogen manifest

### PR DESCRIPTION
**Pull request by EternityForest**

### CODE REVIEW

**Comment by Azgaar** [comment]
Please see the comments in #72

**Comment by EternityForest** [comment]
Ah, just saw that.  It is a bit complicated to create the manifest, but it does have the advantage of keeping things standard in case of any future extra features that use the manifest, but I do agree that an array works just as well.

**Comment by Azgaar** [comment]
Hello @EternityForest,

Are you going to continue to work on it or is it done? I would prefer to generate a flat list of languages, in this case we can toggle off manifest generation from Crowdin and use only gitHub integration

**Comment by EternityForest** [comment]
Just waiting to hear back! Somewhat busy over the holidays but I can work on this some more.

This branch should be close to done, I think it just needs to be updated to not generate a nuisance pull request if the the language files change, but the manifest hasn't.

 It doesn't use Crowdin's manifest generation at all, it just makes a flat list based on the set of languages folders, and edits the manifest file to contain the new list, so it should work entirely with integrations.

It would be easy enough to just ditch the manifest and store the list somewhere else though.  Where should the list be stored though?

**Review by Azgaar — APPROVED** [review]

**Pull request merged**
